<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Amasty\Shopby\Block\Product\ProductList\ChildrenCategoryList;

/** @var Escaper $escaper */
/** @var ChildrenCategoryList $block */
/** @var ViewModelRegistry $viewModels */
/** @var Magento\Catalog\Model\Category[] $categories */

$categories = $block->getChildrenCategories();
$size = $block->getImageSize();
$uniqueId = '_' . uniqid();
$isSliderEnabled = $block->isSliderEnabled();
$swiperPrefix = $isSliderEnabled ? 'swiper-' : '';
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<!-- Category Children Hyva -->
<?php if (count($categories)): ?>
    <div class="container">
        <div class="amslider-container mx-auto amwidget-children-categories my-5
            <?= $escaper->escapeHtmlAttr($isSliderEnabled ? 'am-swiper-slider w-full opacity-0 h-[' . $escaper->escapeHtml($size) . 'px]' : ''); ?>"
            <?= $isSliderEnabled ? 'x-data="amShopBySwiperSlider' . $escaper->escapeJs($uniqueId) . '()"' : '' ?>>
            <div class="amslider amshopby-categories-slider relative" id="category-carousel">
                <?php if ((count($categories) > $block->getItemsCountPerSlide()) && $block->isSliderEnabled()): ?>
                    <button class="swiper-button-prev"
                            data-amshopby-js="children-category-swiper-prev"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>"
                            title="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>"></button>
                    <button class="swiper-button-next"
                            data-amshopby-js="children-category-swiper-next"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Next')) ?>"
                            title="<?= $escaper->escapeHtmlAttr(__('Next')) ?>"></button>
                <?php endif; ?>
                <div class="children-category-container <?= /* @noEscape */ $swiperPrefix ?>container">
                    <div class="<?= /* @noEscape */ $swiperPrefix ?>wrapper justify-center py-2 <?= !$block->isSliderEnabled() ? 'flex flex-wrap w-full' : ''; ?>">
                        <?php foreach ($categories as $category): ?>
                            <?php $imgUrl = $block->getCategoryImageUrl($category, $size) ?>
                            <?php $imgAlt = __('Category') . ' ' . $category->getName() . ' ' . __('image') ?>
                            <?php if ($imgUrl): ?>
                                <a title="<?= $escaper->escapeHtmlAttr($category->getName()) ?>"
                                   href="<?= $escaper->escapeUrl($category->getUrl()) ?>"
                                   class="<?= /* @noEscape */ $swiperPrefix; ?>slide bg-white">
                                <span class="<?= /* @noEscape */ $swiperPrefix ?>category-item block 
                                    <?= /* @noEscape */ ($block->showLabels()) ? ' category-item-label' : '' ?>">
                                    <?php if (!$block->isOnlyLabels()): ?>
                                        <img class="block mx-auto" height="<?= /* @noEscape */ $size ?>"
                                             width="<?= /* @noEscape */ $size ?>"
                                             src="<?= $escaper->escapeUrl($imgUrl) ?>"
                                             alt="<?= $escaper->escapeHtmlAttr($imgAlt)?>"/>
                                    <?php endif; ?>

                                    <?php if ($block->showLabels() || $block->isOnlyLabels()): ?>
                                        <div class="category-item-title w-full"
                                            <?php $style = 'style="max-width: ' . $size . 'px"' ?>
                                            <?= /* @noEscape */ $block->isSliderEnabled() ? '' : $style ?>
                                        >
                                            <?= $escaper->escapeHtml($category->getName()) ?>
                                        </div>
                                    <?php endif; ?>
                                </span>
                                </a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($isSliderEnabled): ?>
    <script>
        function amShopBySwiperSlider<?= $escaper->escapeJs($uniqueId) ?>() {
            return {
                initSwiper(selector) {
                    return new Swiper(selector, {
                        slidesPerView: 1,
                        loop: true,
                        simulateTouch: true,
                        breakpoints: {
                            320: {
                                slidesPerView: 1,
                                spaceBetween: 10
                            },
                            480: {
                                slidesPerView: 2,
                                spaceBetween: 20
                            },
                            768: {
                                slidesPerView: "<?= /* @noEscape */ $block->getItemsCountPerSlide()?>",
                                spaceBetween: 20
                            }
                        },
                        navigation: {
                            nextEl: "[data-amshopby-js=\"children-category-swiper-next\"]",
                            prevEl: "[data-amshopby-js=\"children-category-swiper-prev\"]"
                        },
                        spaceBetween: 30,
                        a11y: {
                            slideLabelMessage: "slide {{index}} of {{slidesLength}} slide",
                            itemRoleDescriptionMessage: "This is a slide for a child category filter"
                        }
                    });
                },

                init() {
                    const sliderSelector = '.amwidget-children-categories .swiper-container';
                    if (!window.Swiper) {
                        window.addEventListener('amSwiperLoaded', () => {
                            this.setupSwiper(this.$el, sliderSelector);
                        });
                        this.initializeSwiper();
                    } else {
                        this.setupSwiper(this.$el, sliderSelector);
                    }
                },

                setupSwiper(element, sliderSelector) {
                    element.classList.remove('opacity-0');
                    element.classList.remove(`h-[<?= /** @noEscape */ $size; ?>px]`);
                    this.initSwiper = this.initSwiper(sliderSelector);
                    this.initSwiper.init();
                },

                initializeSwiper() {
                    if (window._amSwiperLoaded) {
                        return;
                    }

                    // load swiper
                    const script = document.createElement('script');
                    script.src = '<?= $escaper->escapeUrl($block->getViewFileUrl('Amasty_ShopByBrandHyvaCompatibility::js/swiper.min.js')) ?>';
                    script.async = true;
                    document.body.appendChild(script);

                    window._amSwiperLoaded = true;

                    script.onload = () => {
                        window.dispatchEvent(new CustomEvent('amSwiperLoaded', {}));
                    }

                    const styles = document.createElement('link');
                    styles.rel = 'stylesheet';
                    styles.href = '<?= $escaper->escapeUrl($block->getViewFileUrl('Amasty_ShopByBrandHyvaCompatibility::css/swiper.min.css')) ?>';

                    document.head.appendChild(styles);
                }
            }
        }
    </script>
<?php endif; ?>


