<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart\Coupon;
use Magento\Framework\Escaper;

/** @var Coupon $block */
/** @var Escaper $escaper */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = (bool)strlen($block->getCouponCode() ?: "");
?>
<script>
    function initCouponForm() {
        return {
            showCouponForm: <?= $hasCouponCode ? 1 : 0 ?>,
            formData: {
                coupon_code: '<?= $escaper->escapeJs($block->getCouponCode()) ?>',
                remove: '<?= (int)$hasCouponCode ?>'
            },
            init() {
                this.showCouponForm = JSON.parse(hyva.getBrowserStorage().getItem('hyva.showCouponForm'))
            },
            toggleShowCoupon() {
                this.showCouponForm = !this.showCouponForm;

                hyva.getBrowserStorage().setItem('hyva.showCouponForm', this.showCouponForm);

                this.$nextTick(() => this.$refs.couponInput.select());
            }
        }
    }
</script>
<div class="coupon-form bg-white border-b-2 border-gray-200 py-3 shadow-md" x-data="initCouponForm()"
     :class="{'my-4 rounded-lg': showCouponForm}">
    <div class="mx-auto md:mx-0">
        <button @click="toggleShowCoupon()" class="flex items-center justify-between w-full px-4"
                id="discount-form-toggle" :aria-expanded="showCouponForm" type="button">
            <span class="flex items-center gap-1">
                <span
                    class="checkout-cart-icon bg-no-repeat bg-[length:1600%] bg-[position:-331px_-54px] h-8 w-10 block"></span>
                <span>
                    <?= $escaper->escapeHtml(__('Discount Coupon')) ?>
                </span>
            </span>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" class="border border-violet-800 w-6 h-6 block"
                 viewBox="0 0 24 24" stroke="currentColor" focusable="false" style="color: #8b2692;">
                <path x-show="!showCouponForm" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M19 9l-7 7-7-7" style="display: none;"></path>
                <path x-show="showCouponForm" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M5 15l7-7 7 7"></path>
            </svg>
        </button>

        <div>
            <form id="discount-coupon-form" class="m-4" x-show="showCouponForm" x-cloak
                  action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>" method="post"
                  @submit.prevent="hyva.postCart($event.target)">
                <?= $block->getBlockHtml('formkey') ?>

                <div class="fieldset coupon">

                    <input type="hidden" name="remove" id="remove-coupon" value="<?= (int)$hasCouponCode ?>"/>

                    <div class="flex flex-col gap-2 justify-center">
                        <label for="coupon_code" class="label sr-only">
                            <?= $escaper->escapeHtml(__('Enter discount code')) ?>
                        </label>
                        <div class="control">
                            <input type="text"
                                   class="form-input disabled:opacity-75 disabled:bg-gray-100 disabled:pointer-events-none w-full"
                                   id="coupon_code" name="coupon_code"
                                   value="<?= $escaper->escapeHtmlAttr($block->getCouponCode()) ?>"
                                   x-model="formData.coupon_code" x-ref="couponInput"
                                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter discount code')) ?>"
                                <?php if ($hasCouponCode): ?> disabled <?php else: ?> required <?php endif; ?> />
                        </div>

                        <div>
                            <?php if (!$hasCouponCode): ?>
                                <div class="mt-2">
                                    <button class="btn btn-outline w-full" type="submit"
                                            value="<?= $escaper->escapeHtmlAttr(__('Apply')) ?>">
                                        <span><?= $escaper->escapeHtml(__('Apply')) ?></span>
                                    </button>
                                </div>
                            <?php else: ?>
                                <div class="mt-2">
                                    <button type="submit" class="btn btn-outline w-full"
                                            value="<?= $escaper->escapeHtmlAttr(__('Cancel')) ?>">
                                        <?= $escaper->escapeHtml(__('Cancel')) ?>
                                    </button>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
