<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Link $block */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <a @click.prevent.stop="$dispatch('toggle-authentication',
        {url: '<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getUrl('checkout/index'))) ?>'});"
       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getUrl('checkout/index'))) ?>"
       title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
       class="btn btn-primary rounded-3xl py-2 uppercase" id="checkout-link-button">
        <?= $escaper->escapeHtml(__('Proceed to Checkout')) ?>
    </a>
<?php endif ?>
