<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<template x-if="segment.code === 'discount'">
    <div class="flex my-2 text-md lg:text-sm md:grid md:grid-cols-2 md:w-full">
        <div class="w-7/12 text-left md:w-auto" x-html="segment.title"></div>
        <div class="w-5/12 text-right md:w-auto" x-text="hyva.formatPrice(segment.value)"></div>
    </div>
</template>
