<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ForgotPasswordButton;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\StoreSwitcher;
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var Forgotpassword $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var ForgotPasswordButton $forgotPasswordButtonViewModel */
/** @var ViewModelRegistry $viewModels */

$forgotPasswordButtonViewModel = $viewModels->require(ForgotPasswordButton::class);
$storeConfig = $viewModels->require(StoreConfig::class);
$isAutocompleteEnabled = $storeConfig->getStoreConfig('customer/password/autocomplete_on_storefront');
$formId = 'user_forgotpassword';

$storeSwitcherViewModel = $viewModels->require(StoreSwitcher::class);
$storeName = $storeSwitcherViewModel->getStore()->getName();

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');

// Set email based on store name
$email = ($storeName === 'USA') ? 'support@ginoi.com' : 'atencionalcliente@ginoi.com';
?>
<div class="flex mt-10 justify-center">
    <div class="w-full md:w-[525px] rounded-lg border-gray-300 border" >
        <div class="p-6 md:p-8">
            <legend class="mb-3">
                <h2 class="text-2xl title-font text-primary font-bold">
                    <?= $escaper->escapeHtml(__('Password Recovery')) ?>
                </h2>
            </legend>
            <form action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
                  method="post"
                  id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                  x-data="initPasswordForm()"
                  @submit.prevent="submitForm();">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($formId) ?>"/>
                <?= $block->getChildHtml('form_fields_before') ?>

                <fieldset class="fieldset">
                    <p class="mb-2 text-lg"><span><?= $escaper->escapeHtml(__('We can')) ?></span><span class="ml-1 text-[#471CFF]"><?= $escaper->escapeHtml(__('help you')) ?></span></p>
                    <div class="text-[#3F07AF] mb-4 bg-[#F8F5FF] p-2 md:p-4 rounded"><?= $escaper->escapeHtml(
                            __('Please enter your email address below to receive a password reset link.')
                        ) ?></div>
                    <div class="field email required">
                        <label for="email_address" class="label">
                            <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                        </label>
                        <div class="control">
                            <input type="email"
                                   name="email"
                                   alt="email"
                                   id="email_address"
                                   class="form-input w-full"
                                   autocomplete="<?= $isAutocompleteEnabled ? 'username' : 'off' ?>"
                                   required
                                   value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="my-4">
                        <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
                        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
                    </div>
                </fieldset>
                <button type="submit" class="btn btn-primary disabled:opacity-75 w-full justify-center uppercase bg-[#802E8D]"
                    <?php if ($forgotPasswordButtonViewModel->disabled()): ?> disabled data-recaptcha-btn<?php endif; ?>
                >
                    <span><?= $escaper->escapeHtml(__('Reset My Password')) ?></span>
                </button>
                <p class="mt-4"><a class="underline underline-offset-3 text-[#802E8D] hover:font-bold"
                      href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>"><span><?= $escaper->escapeHtml(__('Go Back')) ?></span></a></p>

            </form>
        </div>

        <div class="border-t border-gray-300 pt-6 px-6 md:px-8 pb-8">
            <p class="text-xl mb-4"><?= $escaper->escapeHtml(__('Has your email changed ?')) ?></p>
            <p><span><?= $escaper->escapeHtml(__('If you no longer use the email address associated with your Ginoi account, you may contact ')) ?></span>
                <a href="mailto:<?= $escaper->escapeUrl($email) ?>" class="mx-1 underline text-[#802E8D] hover:font-bold"><?= $escaper->escapeHtml(__('Customer Service')) ?></a>
                <span><?= $escaper->escapeHtml(__('for help restoring access to your account.')) ?></span></p>
        </div>

    </div>
</div>
<script>
    function initPasswordForm() {
        return {
            errors: 0,
            hasCaptchaToken: 0,
            submitForm() {
                // Do not rename $form, the variable is expected to be declared in the recaptcha output
                const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>

                if (this.errors === 0) {
                    $form.submit();
                }
            }
        }
    }
</script>
