<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreSwitcher;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$storeSwitcherViewModel = $viewModels->require(StoreSwitcher::class);

$storeCode = $storeSwitcherViewModel->getStore()->getCode();
$termsandconditions = 'terminos-condiciones';
$provacypolicy = 'politica-de-privacidad';
$cookies = 'habilitar-cookies';

if($storeCode == 'us'){
    $termsandconditions = 'terms-conditions';
    $provacypolicy = 'privacy-policy';
    $cookies = 'enable-cookies';
}
?>
<div class="text-gray-700 body-font bg-container-darker border-t border-container-darker shadow background-purple">
    <div class="container py-8 w-full px-6 md:px-0">
        <div class="flex flex-wrap order-first gap-y-16">
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName !== 'footer-copyright' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="bg-container border-t border-container flex flex-col sm:flex-row bg-lightpurple items-center px-0 lg:px-5 relative">
    <div class="flex flex-row items-center bg-white shadow-lg p-2 rounded-full relative xl:absolute xl:top-1 xl:left-5 mx-auto h-12 mt-5 sm:mt-0 footer-cur-lang">
    <!-- Globe Icon -->
    <div class="flex items-center justify-center text-white rounded-full h-10 w-10 mr-2">
        <img height="30" width="30" src="<?= $this->getViewFileUrl('images/globe.svg') ?>" alt="">
<!--        <img src="https://www.ginoi.com/media/images/world-icon.png" alt="">-->
    </div>

    <!-- Country Dropdown -->
    <div class="flex items-center space-x-2 mr-2">
    <?= $this->getLayout()->createBlock('Magento\Store\Block\Switcher')->setTemplate('Magento_Store::switch/footer-languages.phtml')->toHtml(); ?>
    </div>

    <!-- Currency Dropdown -->
    <div class="flex items-center space-x-2 mr-2">
    <?= $this->getLayout()->createBlock('Magento\Directory\Block\Currency')->setTemplate('Magento_Directory::footer-currency.phtml')->toHtml(); ?>
    </div>
</div>

    <div class="container py-4 mx-auto flex flex-col sm:flex-row items-center justify-center text-white">
        <p class="text-center sm:text-left text-white">
            <?= $block->getChildHtml('copyright') ?>
        </p>
        <span class="px-3 hidden md:block">|</span>
        <div class="flex flex-wrap justify-center sm:justify-start mt-2 sm:mt-0 gap-2 items-center">
            <a href="<?= $escaper->escapeUrl($block->getUrl($termsandconditions)) ?>" class="text-sm text-white interstatelight contents">
                <?= __('Términos & Condiciones') ?>
            </a>
            <span class="px-3">|</span>
            <a href="<?= $escaper->escapeUrl($block->getUrl($provacypolicy)) ?>" class="text-sm text-white interstatelight contents">
                <?= __('Política de Privacidad') ?>
            </a>
            <span class="px-3">|</span>
            <a href="<?= $escaper->escapeUrl($block->getUrl($cookies)) ?>" class="text-sm text-white interstatelight contents">
                <?= __('Habilitar Cookies') ?>
            </a>
        </div>
    </div>
</div>

</div>

