<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$route = $request->getRouteName() . '/' . $request->getActionName() . '/' . $request->getControllerName();
$textSizeCssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : ' text-2xl';
if ($route == "catalog/view/category") {
    $titleContainerClasses = $block->getData('maybe_purged_tailwind_section_classes')
        ?? 'container flex flex-col md:flex-row flex-wrap gap-4 title-css items-center bg-white text-center';
} else {
    $titleContainerClasses = $block->getData('maybe_purged_tailwind_section_classes')
        ?? 'container flex flex-col md:flex-row flex-wrap justify-center py-6 font-bold text-center lg:pt-8 lg:text-3xl';
}

$titleHtml = '';
if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $escaper->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml): ?>
<div class="<?= $escaper->escapeHtmlAttr($titleContainerClasses . $textSizeCssClass) ?>">
    <?php if ($route == "catalog/view/category"): ?>
    <?= $escaper->escapeHtmlAttr(__('Shop by Category / ')) ?>
    <?php endif; ?>
    <h1 class="text-gray-900 page-title title-font font-bold" <?php if ($block->getId()): ?>
        id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>>
        <?= /* @noEscape */
            $titleHtml ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>