
<div class="payment-option" bis_skin_checked="1">

    <div class="container" bis_skin_checked="1">

        <div class="flex flex-wrap payment-option-inner items-center justify-center gap-4" bis_skin_checked="1">

                <ul class="float-left flex justify-center items-center gap-4">

                    <li class="payU inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/PayU.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="achpse inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/ACHPSE.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="VIA inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/VIA.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="baloto inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/BALOTO.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="efecty inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/EFECTY.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="visa inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Visa.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="master-card inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Master-Card.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="american-express inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/American-Express.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li> 

                    <li class="paypal inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Paypal.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="Banco-Bancolombia inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Banco_Bancolombia_Logo.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="Banco-de_Bogota inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Banco_de_Bogota_Logo.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                    <li class="Banco-Davivienda inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Banco_Davivienda_Logo.svg'); ?>' alt="payU-icon" style="height: 26px;width: 42px;"></li>

                </ul>
                <span class="text-gray-300 text-4xl hidden md:block">|</span>
                <ul class="float-right flex justify-center items-center">

                    <li class="deprisa inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Deprisa.svg'); ?>' alt="payU-icon" style="height: 40px;width: 115px;"></li>

                    <li class="Interrapidimo inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Interrapidimo.svg'); ?>' alt="payU-icon" style="height: 40px;width: 115px;"></li>

                    <li class="envia inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Envia.svg'); ?>' alt="payU-icon" style="height: 40px;width: 115px;"></li>

                    <li class="Servientrega inline-block"><img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Servientrega.svg'); ?>' alt="payU-icon" style="height: 40px;width: 115px;"></li>

                </ul>


        </div>

    </div>

</div>
