<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="border-t border-gray-300 pt-6 px-8 pb-8">
        <div class="block-title text-lg text-center text-gray-600 pb-6 font-bold !cursor-default">
            <span><?= $escaper->escapeHtml(__('New on')) ?></span><span class="ml-1 text-[#471CFF]"><?= $escaper->escapeHtml(__('Ginoi ?')) ?></span>
        </div>
        <div class="text-center">
            <a href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>"
               class="btn btn-primary bg-white border border-[#802E8D] text-[#802E8D] hover:bg-[#802E8D] hover:text-white disabled:opacity-75 w-full justify-center uppercase"><span><?= $escaper->escapeHtml(__('Create an Account')) ?></span></a>
        </div>
    </div>
<?php endif; ?>
