<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div
    class="relative inline-block hidden md:hidden lg:block"
    x-data="{ open: false }"
    @keyup.escape="open = false"
    @click.outside="open = false"
>
<div class="flex items-center pr-6 customer-menu" style="border-right: 1px solid gray;">
    <button
        type="button"
        id="customer-menu"
        class="flex gap-1 items-center rounded p-1 hover:bg-primary/10 outline-offset-2"
        @click="open = !open"
        :aria-expanded="open ? 'true' : 'false'"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
        aria-haspopup="true"
    >
    <span class="block w-6 ">
                        <img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/Account.svg'); ?>' alt="icon" class="customer-menu-img">
                    </span>
                    <span class="text-sm interstatelight customer-menu-text"><?= __('Cuenta') ?></span>
                </button>
    </div>
    <nav
        class="
            absolute right-0 z-20 w-40 py-2 mt-2 -mr-4 px-1 overflow-auto origin-top-right rounded-sm
            shadow-lg sm:w-48 lg:mt-3 bg-container-lighter customer-menu-image
        "
        x-cloak
        x-show="open"
        aria-labelledby="customer-menu"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <?= $block->getChildHtml('header.customer.logged.in.links') ?>
        <?php else: ?>
            <?= $block->getChildHtml('header.customer.logged.out.links') ?>
        <?php endif; ?>
    </nav>
</div>
