<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/** @var Renderer $block */
/** @var Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

?>
<tr class="border-b last:border-none border-gray-200 text-left lg:text-center">
    <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>"
        class="p-4 flex flex-wrap gap-8 text-left w-full sm:flex-nowrap lg:w-auto">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>" tabindex="-1"
           class="w-10 h-10 overflow-hidden border border-gray-200 rounded-md">
            <?php else: ?>
            <span>
                <?php endif; ?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                    ->setTemplate('Magento_Catalog::product/image.phtml')
                    ->toHtml() ?>
                <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
    </td>

    <td class="p-4 text-left text-gray-600">
        <?php if ($block->hasProductUrl()): ?>
            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>">
                <?= $escaper->escapeHtml($block->getProductName()) ?>
            </a>
        <?php else: ?>
            <?= $escaper->escapeHtml($block->getProductName()) ?>
        <?php endif; ?>
        <div class="product-item-details grow">
            <?php if ($options = $block->getOptionList()): ?>
                <dl class="item-options w-full break-all mt-1 text-sm !cursor-default clearfix">
                    <?php foreach ($options as $option): ?>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dt class="font-bold float-left clear-left mr-2"><?= $escaper->escapeHtml($option['label']) ?>
                            :
                        </dt>
                        <dd class="float-left">
                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </td>

    <td class="p-4 checkout-cart-price">
        <?= $block->getUnitPriceHtml($item) ?>
    </td>

    <td>
        <div class="field qty">
            <div class="control qty">
                <label for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                    <span class="label sr-only"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                    <input id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                           name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                           value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>" type="number" size="4" step="any"
                           title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                           class="form-input px-2 py-2 w-20 text-center"
                           required min="0" data-role="cart-item-qty"/>
                </label>
            </div>
        </div>
    </td>

    <td class="p-4 checkout-cart-price">
        <?= $block->getRowTotalHtml($item) ?>
    </td>
    <?= /* @noEscape */ $block->getActions($item) ?>
</tr>
