<?php declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Mega Menu Lite Hyva
 */

use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Amasty\MegaMenuLite\Block\Container;
use Amasty\MegaMenuLite\ViewModel\Store\Menu;
use Amasty\MegaMenuLiteHyva\ViewModel\DesktopMenuItem;
use Hyva\Theme\ViewModel\StoreConfig;

/**
 * @var Container $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 * @var DesktopMenuItem $menuItemViewModel
 * @var array $item
 **/

/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);

/** @var Menu $viewModelMenu */
$viewModelMenu = $viewModels->require(Menu::class);

/** @var DesktopMenuItem $menuItemViewModel */
$menuItemViewModel = $viewModels->require(DesktopMenuItem::class);

$menuItemViewModel->setBlock($block);
$menuItems = $block->getNodesData()['elems'];

/* MegaMenuAddon custom code */
$storeConfigViewModel = $viewModels->require(StoreConfig::class);
$walmartStyleEnabled = $storeConfigViewModel->getStoreConfig('ammegamenu/general/walmart_like_enabled') ?: false;

// phpcs:disable Generic.Files.LineLength.TooLong
?>
<?php if (!$walmartStyleEnabled) : ?>
<aside class="bg-[var(--ammenu-main-menu-background)] box-content fixed z-50 font-normal text-base shadow-lg py-5 max-w-lg w-[95vw] top-0 bottom-0 left-0 overflow-y-auto"
       x-transition:enter="transition ease-in-out duration-500 transform"
       x-transition:enter-start="-translate-x-12 opacity-0 duration-700"
       x-transition:enter-end="translate-x-0 opacity-100"
       x-transition:leave="transition ease-in-out duration-500"
       x-transition:leave-start="opacity-100 translate-x-0"
       x-transition:leave-end="opacity-0 -translate-x-12"
       x-show="open"
       role="navigation"
       x-cloak>

    <h2 class="aside-title py-2 ml-14 mb-2 flex justify-between items-center mr-6 font-bold text-lg">
        <span class="text-[var(--ammenu-main-menu-text)]" x-text="mobile_menu_title"></span>
        <button @click="open = false" type="button" class="text-[var(--ammenu-toggle-icon-color)]">
            <?= $heroIcons->xHtml(''); ?>
        </button>
    </h2>

    <?= /** @noEscape */ $menuItemViewModel->fetchView('components/tab-menu-wrapper.phtml') ?>
    <?php endif; ?>

    <template x-if="open">
        <nav aria-label="<?= $escaper->escapeHtmlAttr(__('Main Menu'))  ?>">
            <ul class="flex flex-col flex-nowrap mb-6" role="menubar" data-action="amMenuMenubar">
                <?php foreach ($menuItems as $key => $item): ?>
                    <?php if ($item['status'] === 1 || $item['status'] === 3): ?>
                        <?php if ($walmartStyleEnabled) {
                            /** @noEscape */ echo $menuItemViewModel->fetchView(
                                'components/mobile_menu/submenu-item.phtml',
                                ['item' => $item, 'isFirst' => true],
                                "Amasty_MegaMenuHyvaAddon::%s"
                            );
                        } else {
                            /** @noEscape */ echo $menuItemViewModel->fetchView(
                                'components/mobile_menu/submenu-item.phtml',
                                ['item' => $item, 'isFirst' => true]
                            );
                        }
                        ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>

            <!-- Menu Pro / Drill -->
            <?= /** @noEscape */ $block->getChildHtml('ammenu.menu.mobile.drill'); ?>
            <!-- /Menu Pro -->
        </nav>
    </template>
<?php if (!$walmartStyleEnabled) : ?>
</aside>
<?php endif; ?>

