<?php $label = __('Order Tracking'); ?>
<a id="customer.header.order.link"
       class="flex gap-2 py-2 lg:py-2 hover:bg-gray-100 px-2 items-center"
       href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
       title="<?= $escaper->escapeHtmlAttr($label) ?>"
    >
        <img src='<?php echo $this->getViewFileUrl('Magecomp_Hyvachildtheme::image/track_orders.svg'); ?>' alt="Order Tracking" class="w-6">
        <span class="text-sm"><?= $escaper->escapeHtml($label) ?></span>
    </a>