<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package GDPR Cookie Hyva Compatibility (System)
 */

use Amasty\GdprCookieHyva\ViewModel\CookieBarSettings;
use Amasty\GdprCookieHyva\ViewModel\Settings;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */

$groupBlockName = $block->getData('group_block_name');
$settings = $viewModels->require(Settings::class);
?>

<div x-data="{...hyva.modal(), ...initCookieBarSettings()}" x-spread="eventListeners" x-bind="eventListeners">
    <div x-cloak x-spread="overlay('<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>')"
         x-bind="overlay('<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>')"
         class="fixed inset-0 flex flex-col items-center justify-center text-left bg-gray-500/50 z-50 <?= /* @noEscape */ CookieBarSettings::REF_NAME ?>">
        <div x-ref="<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>" role="dialog" aria-labelledby="cookiebar-groups"
             class="relative inline-block max-h-screen-85 overflow-auto text-gdpr
                max-w-[90vw] lg:max-w-2xl bg-white shadow-xl rounded-md border border-gray-200">
            <div tabindex="0" @focusin="focusDoneButton()"></div>
            <div class="flex items-center border-b border-gray-200 py-3 px-10">
                <?= $block->getChildHtml('amasty.gdpr.logo') ?>
                <button @click="$dispatch(hide('<?= /* @noEscape */ CookieBarSettings::CLOSE_ACTION ?>'))"
                        aria-label="<?= $escaper->escapeHtml(__('Close')) ?>"
                        x-ref="ambar-settings-close"
                        class="absolute right-2 top-2 text-gray-300 transition
                            hover:text-black focus:drop-shadow-md hover:drop-shadow-md">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                         stroke="currentColor"
                         stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                </button>
            </div>
            <div class="">
                <div class="px-10 pt-5">
                    <?= $block->getChildHtml('amasty.gdpr.popup.msg') ?>
                </div>
                <div id="cookiebar-groups" class="pt-5">
                    <strong class="block mb-3 mx-10"><?= $escaper->escapeHtml(__('Manage Consent Preferences'))?></strong>
                    <div class="rounded border border-t-transparent border-gray-200 mx-10 mb-5">
                        <?= $block->getChildHtml($groupBlockName ?: 'amasty.cookie.cookiebar.groups') ?>
                    </div>
                    <div class="w-full flex items-center justify-end py-5 px-10 border-t border-gray-200 gap-4">
                        <button class="ambar-btn-accept px-8 py-2 btn btn-primary justify-center rounded-full bg-purple"
                                @click="uncheckToggles()">
                            <?= $escaper->escapeHtml(__("Reject All")) ?>
                        </button>
                        <button class="ambar-btn-accept px-8 py-2 btn btn-primary justify-center rounded-full bg-purple"
                                x-ref="ambar-settings-done"
                                x-focus-first
                                @click="$dispatch('cookiebar-action-accept', $store.AmastyCookieGroups.getCheckedGroupIds())">
                            <?= $escaper->escapeHtml($settings->getCookieSettingsBarDoneButtonText()) ?>
                        </button>
                    </div>
                </div>
            </div>
            <div tabindex="0" @focusin="focusCloseButton()"></div>
        </div>
    </div>
</div>

<script>
    'use strict';

    function initCookieBarSettings() {
        return {
            eventListeners: {
                ['@<?= /* @noEscape */ CookieBarSettings::CLOSE_ACTION ?>.window']() {
                    !!this.opened['<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>'] &&
                    this.hide('<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>');
                },
                ['@<?= /* @noEscape */ CookieBarSettings::OPEN_ACTION ?>.window']() {
                    !this.opened['<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>'] &&
                    this.show('<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>');
                    this.checkToggles();
                },
                ['@cookiebar-action-accept-finish.window']() {
                    !!this.opened['<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>'] &&
                    this.hide('<?= /* @noEscape */ CookieBarSettings::REF_NAME ?>');
                }
            },
            focusDoneButton: function () {
                this.$refs['ambar-settings-done']?.focus();
            },
            focusCloseButton: function () {
                this.$refs['ambar-settings-close']?.focus();
            },
            uncheckToggles: function() {
                document.querySelectorAll('.gdpr-toggle').forEach(_checkbox=>{
                    (_checkbox).checked = false;
                    let event = new Event('change');
                    (_checkbox).dispatchEvent(event);
                    });
            },
            checkToggles: function() {
                document.querySelectorAll('.gdpr-toggle').forEach(_checkbox=>{
                    (_checkbox).checked = true;
                    let event = new Event('change');
                    (_checkbox).dispatchEvent(event);
                    });
            }
        }
    }
</script>
