<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var Currency $currencyViewModel */
$currencyViewModel = $viewModels->require(Currency::class);
?>
<?php if ($currencyViewModel->getCurrencyCount() > 1): ?>
    <?php $currencies = $currencyViewModel->getCurrencies(); ?>
    <?php $currentCurrencyCode = $currencyViewModel->getCurrentCurrencyCode(); ?>
    <div x-data="{ open: false }">
        <div class="relative inline-block text-left">
                <button @click.prevent="open = !open"
                        @click.outside="open = false"
                        @keydown.window.escape="open=false"
                        type="button"
                        class="inline-flex justify-center w-full text-sm gap-2 items-center interstatelight"
                        aria-haspopup="true"
                        :aria-expanded="open"
                >
                <?php $flagImage = 'Magecomp_Hyvachildtheme::image/'.$block->getCurrentCurrencyCode().'.png'; ?>
                <img src="<?= $this->getViewFileUrl($flagImage); ?>">
                    <?= $escaper->escapeHtml(__('Moneda')) ?>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-4 h-4"><path d="M233.4 406.6c12.5 12.5 32.8 12.5 45.3 0l192-192c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L256 338.7 86.6 169.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l192 192z"></path></svg>
                </button>
                <div class="pin-hover hidden"></div>
            <nav x-cloak=""
                 
                 class="absolute right-0 top-full z-20 w-full lg:w-56 py-2 overflow-auto origin-top-left rounded-lg shadow-lg sm:w-48 currency-hover bg-container-lighter"
                 aria-labelledby="currency-heading"
            >
                <div class="my-1">
                    <?php foreach ($currencies as $code => $name): ?>
                            <button
                               role="link"
                               class="flex px-4 py-2 lg:px-5 lg:py-2 gap-1 items-center w-full <?php if($block->getCurrentCurrencyCode() == $code) :?> active-flag<?php endif; ?>"
                               aria-describedby="currency-heading"
                               @click.prevent='hyva.postForm(<?= /* @noEscape */ $currencyViewModel->getSwitchCurrencyPostData($code) ?>)'
                            >
                            <?php $flagImage = 'Magecomp_Hyvachildtheme::image/'.$code.'.png'; ?>
                            <img src="<?= $this->getViewFileUrl($flagImage); ?>">
                            <?php if($code == 'COP'): ?>
                            <span class="text-sm interstatelight currency-name"><?= $escaper->escapeHtml(__('Pesos - $ COP')) ?></span>
                            <?php endif; ?>
                            <?php if($code == 'USD'): ?>
                            <span class="text-sm interstatelight currency-name"><?= $escaper->escapeHtml(__('Dólares - $ USD')) ?></span>
                            <?php endif; ?>
                            </button>
                    <?php endforeach; ?>
                </div>
            </nav>
        </div>
    </div>
<?php endif; ?>
