<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit;
use Magento\Framework\Escaper;

/** @var Edit $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$item = $block->getItem();

if ($item->getProductType() === 'configurable') {
    $productOptions = $item->getProduct()->getTypeInstance()->getOrderOptions($item->getProduct());
    $productName = $productOptions["simple_name"];
} else {
    $productName = $item->getName();
}
?>
<td class="p-4" data-th="<?= $escaper->escapeHtml(__('edit')); ?>">
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit" href="<?= $escaper->escapeUrl($block->getConfigureUrl()) ?>"
       aria-label="<?= $escaper->escapeHtmlAttr(__('Edit %1', $productName)) ?>">
    <span
        class="checkout-cart-icon bg-no-repeat bg-[length:1800%] bg-[position:-92px_-44px] hover:bg-[position:-92px_-85px] hover:transition-none h-8 w-8 inline-block"></span>
    </a>
<?php endif ?>
</td>
