<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove;
use Magento\Framework\Escaper;

/** @var Remove $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$item = $block->getItem();

if ($item->getProductType() === 'configurable') {
    $productOptions = $item->getProduct()->getTypeInstance()->getOrderOptions($item->getProduct());
    $productName = $productOptions["simple_name"];
} else {
    $productName = $item->getName();
}
?>
<td class="p-4" data-th="<?= $escaper->escapeHtml(__('remove')); ?>">
    <button class="action-delete" x-data="{}"
            @click.prevent='hyva.postForm(<?= /* @noEscape */
            $block->getDeletePostJson() ?>)'
            aria-label="<?= $escaper->escapeHtmlAttr(__('Remove %1', $productName)) ?>" type="button">
        <span
            class="checkout-cart-icon bg-no-repeat bg-[length:1800%] bg-[position:-164px_-43px] hover:bg-[position:-164px_-85px] hover:transition-none h-8 w-8 inline-block"></span>
    </button>
</td>
