<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package GDPR Cookie Hyva Compatibility (System)
 */

use Amasty\GdprCookie\Block\Widget\Settings;
use Amasty\GdprCookieHyva\ViewModel\CookieBarSettings;
use Amasty\GdprCookieHyva\ViewModel\CookieGroupInfo;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Settings $block */
/** @var Escaper $escaper */

if (!$block->isNeedToShow()) {
    return;
}

$groupInfoPrefix = 'widget-';
$openGroupInfoAction = $groupInfoPrefix . CookieGroupInfo::OPEN_ACTION;
$groupInfoBlock = $block->getLayout()
    ->createBlock(Template::class, 'amasty.cookie.cookiewidget.groups.info')
    ->setTemplate('Amasty_GdprCookieHyva::modal/cookie-group-info.phtml')
    ->setData('prefix', $groupInfoPrefix);
?>

<section x-data class="w-full flex flex-col <?= /* @noEscape */ CookieBarSettings::REF_NAME ?>">
    <div class="md:mb-2 flex items-center justify-center
                            px-4 flex-wrap sm:flex-nowrap sm:justify-between">
        <h3 class="text-lg font-semibold">
            <?= $escaper->escapeHtml(__('Cookie Settings')) ?>
        </h3>
        <div class="flex">
            <button data-role="action" class="p-4 ml-4 mb-2 w-full text-xs font-semibold rounded-sm
                           leading-none text-center text-white uppercase bg-primary btn-primary"
                    aria-label="<?= $escaper->escapeHtml(__('Allow All Cookies')) ?>"
                    @click.prevent="$dispatch('cookiebar-action-allow')">
                <?= $escaper->escapeHtml(__('Allow All Cookies')) ?>
            </button>
            <button data-role="action" class="p-4 ml-4 mb-2 w-full text-xs font-semibold rounded-sm
                           leading-none text-center text-white uppercase bg-primary btn-primary"
                    aria-label="<?= $escaper->escapeHtml(__('Save')) ?>"
                    @click.prevent="$dispatch('cookiebar-action-accept', $store.AmastyCookieGroups.getCheckedGroupIds())">
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>
        </div>
    </div>

    <template x-for="group in $store.AmastyCookieGroups.groupData" :key="group.groupId">
        <div class="mb-2">
            <div class="header flex justify-between items-start py-2">
                <h3 class="text-lg font-semibold pr-6" x-text="group.name"></h3>
                <div>
                    <label :for="`switchBox-${group.groupId}`">
                        <input type="checkbox"
                               name="groups[]"
                               x-model="group.checked"
                               :id="`switchBox-${group.groupId}`"
                               :disabled="group.isEssential"
                               :value="group.groupId"
                               :aria-label="group.name"
                               class="amsettings-bar-input-toggle"
                               :class="{'!bg-gray-400': group.isEssential}">
                    </label>
                </div>
            </div>
            <template x-if="group.description">
                <p class="py-2 text-sm" x-html="group.description"></p>
            </template>
            <button class="btn btn-primary uppercase text-xs text-center text-white font-semibold leading-none
                        p-4 mt-4 rounded-sm before:content-none after:content-none
                        focus:drop-shadow-sm hover:drop-shadow-sm"
                    type="button"
                    title="<?= $escaper->escapeHtml(__('More Information')) ?>"
                    aria-label="<?= $escaper->escapeHtml(__('More Information')) ?>"
                    @click="$dispatch('<?= $escaper->escapeHtml($openGroupInfoAction) ?>', group)">
                <?= $escaper->escapeHtml(__('More Information')) ?>
            </button>
        </div>
    </template>
</section>

<?= $groupInfoBlock->toHtml() ?>
