<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Items;

/** @var Escaper $escaper */
/** @var Items $block */
$columns = $block->getColumns();
?>
<style>
     .table-wishlist td{
        text-align: center;
        vertical-align: middle;
    }
     table {
         border-collapse: separate;
         border-spacing: 0;
     }
     table tr:last-child td {
         border-bottom-width: 1px;
     }

     table tr th:first-child,
     table tr td:first-child {
         border-left-width: 1px;
     }
     table tr th {
         border-top-width: 1px;
     }
     .action-btn:hover {
         filter: invert(13%) sepia(98%) saturate(7464%) hue-rotate(270deg) brightness(65%) contrast(120%);
         transition: none;
     }
     .cancel-btn:hover {
         filter: sepia(97%) saturate(7496%);
         transition: none;
     }
</style>
<div class="products-grid wishlist overflow-auto">
    <?php if (count($block->getItems())): ?>
    <table class="table-wishlist w-full sm:table-fixed lg:table-auto">
        <thead class="text-sm text-secondary">
        <tr>
            <th class="py-2 pr-2 pl-4 text-center text-primary-purple rounded-tl-xl">
                <span class="lg:hidden"><?= $escaper->escapeHtmlAttr('Product') ?></span>
                <span class="hidden lg:block"><?= $escaper->escapeHtmlAttr('Image') ?></span>
            </th>
            <th class="p-2 text-start text-primary-purple hidden lg:table-cell "><?= $escaper->escapeHtmlAttr('Product Description') ?></th>
            <th class="p-2 text-center text-primary-purple hidden lg:table-cell"><?= $escaper->escapeHtmlAttr('Unit Price') ?></th>
            <th class="p-2 text-start text-primary-purple hidden lg:table-cell"><?= $escaper->escapeHtmlAttr('Notes') ?></th>
            <th class="p-2 text-center text-primary-purple hidden lg:table-cell">
                <p><?= $escaper->escapeHtmlAttr('Quantity') ?></p>
                <p class="font-thin text-sm">(<?= $escaper->escapeHtmlAttr('Units') ?>)</p>

            </th>
            <th class="p-2 text-center text-primary-purple lg:hidden">
                <span><?= $escaper->escapeHtmlAttr('Notes') ?></span>
                /
                <span><?= $escaper->escapeHtmlAttr('Quantity') ?></span>
            </th>
            <th class="p-2 text-center text-primary-purple hidden lg:table-cell"><?= $escaper->escapeHtmlAttr('Add to Cart') ?></th>
            <th class="p-2 text-center text-primary-purple hidden lg:table-cell"><?= $escaper->escapeHtmlAttr('Edit') ?></th>
            <th class="p-2 text-center text-primary-purple hidden lg:table-cell border-r rounded-tr-xl"><?= $escaper->escapeHtmlAttr('Delete') ?></th>
            <th class="p-2 text-center text-primary-purple lg:hidden border-r rounded-tr-xl">
                <div class="flex gap-1 justify-center flex-wrap flex-col sm:flex-row">
                    <span><?= $escaper->escapeHtmlAttr('Add to Cart') ?> /</span>
                    <span><?= $escaper->escapeHtmlAttr('Edit') ?> /</span>
                    <span><?= $escaper->escapeHtmlAttr('Delete') ?></span>
                </div>

            </th>
        </tr>
        </thead>
        <tbody>

        <?php
            $array = $block->getItems()->getData();
            $total = count($array);
            $count = 0;
        ?>
        <?php foreach ($block->getItems() as $item): ?>
            <?php
            $count++;
            $roundedClassFirst = ($count === $total) ? 'rounded-bl-xl' : '';
            $roundedClassLast = ($count === $total) ? 'rounded-br-xl' : '';

             $imageBlock = $block->getChildBlock("customer.wishlist.item.image")->setItem($item);
             $nameBlock = $block->getChildBlock("customer.wishlist.item.name")->setItem($item);
             $priceBlock = $block->getChildBlock("customer.wishlist.item.price")->setItem($item);

             $innerBlock = $block->getChildBlock("customer.wishlist.item.inner");
             $commentBlock = $innerBlock->getChildBlock('customer.wishlist.item.comment')->setItem($item);
             $cartBlock = $innerBlock->getChildBlock('customer.wishlist.item.cart')->setItem($item);
             $quantityBlock  = $innerBlock->getChildBlock('customer.wishlist.item.cart.quantity')->setItem($item);

             $actionBlock = $innerBlock->getChildBlock('customer.wishlist.item.actions');
             $editButton = $actionBlock->getChildBlock('customer.wishlist.item.edit')->setItem($item);
             $removeButton = $actionBlock->getChildBlock('customer.wishlist.item.remove')->setItem($item);
            ?>
        <tr class="align-top bg-container-purple">
            <td class="py-2 pr-2 pl-4 text-start font-normal <?= $roundedClassFirst ?>">
                <?= $imageBlock->toHtml() ?>
                <div class="lg:hidden text-sm">
                    <div class="mb-2">
                        <?= $nameBlock->toHtml() ?>
                    </div>
                    <div class="text-start">
                        <?= $priceBlock->toHtml() ?>
                    </div>

                </div>
            </td>
            <td class="p-2 hidden lg:table-cell">
                <?= $nameBlock->toHtml() ?>
            </td>
            <td class="p-2 hidden lg:table-cell">
                <?= $priceBlock->toHtml() ?>
            </td>
            <td class="p-2 hidden lg:table-cell">
                <?= $commentBlock->toHtml() ?>
            </td>
            <td class="p-2 hidden lg:table-cell">
                <?= $quantityBlock->toHtml() ?>
            </td>
            <td class="p-2  lg:hidden text-gray-600">
                    <p class="text-start mb-2"><?= $escaper->escapeHtmlAttr('Notes') ?></p>
                    <?= $commentBlock->toHtml() ?>
                    <br>
                    <p class="text-start mb-2"><?= $escaper->escapeHtmlAttr('Quantity') ?></p>
                    <?= $quantityBlock->toHtml() ?>
            </td>
            <td class="p-2 hidden lg:table-cell">
                <?= $cartBlock->toHtml() ?>
            </td>
            <td class="p-2 hidden lg:table-cell">
                <?= $editButton->toHtml() ?>
            </td>
            <td class="p-2 hidden lg:table-cell border-r <?= $roundedClassLast ?>">
                <?= $removeButton->toHtml() ?>
            </td>
            <td class="p-2 lg:hidden border-r <?= $roundedClassLast ?>">
                <div class="flex gap-4 justify-center items-center flex-wrap flex-col sm:flex-row">
                    <?= $cartBlock->toHtml() ?>
                    <?= $editButton->toHtml() ?>
                    <?= $removeButton->toHtml() ?>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $escaper->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column): ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
