<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\BlockJsDependencies;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @var Magento\Catalog\Model\Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$showAddToCompare = $compareViewModel->showInProductList();
$viewIsGrid = $viewMode === 'grid';
$productType = $product->getTypeId();
$isProductGroupedOrBundle = $productType === 'bundle' || $productType === "grouped";
$productId = $product->getId();
$options   = $productOptionsViewmodel->getOptionsData($product);

$hideDetails       = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
$productName = $catalogOutputHelper->productAttribute($product, $product->getName(), 'name');

// Ensure the required JS is rendered on the page
$viewModels->require(BlockJsDependencies::class)->setBlockTemplateDependency($block, 'Magento_Catalog::product/list/js/price-box.phtml');

?>

<?php if ($product->isSaleable()): ?>
<form method="post"
    action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
    class="relative item product product-item product_addtocart_form card card-interactive flex flex-col w-full rounded-lg p-2 <?= $viewIsGrid ? '' : 'md:flex-row' ?>"
    <?php if ($product->getOptions()): ?>
    enctype="multipart/form-data"
    <?php endif; ?>
>
    <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="product" value="<?= (int)$productId ?>"/>
    <?php foreach ($options as $optionItem): ?>
    <input type="hidden"
           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
    <?php endforeach; ?>
    <?php else: ?>
<div class="item product product-item card card-interactive flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>">
<?php endif; ?>
    <?php /* Product Image */ ?>
    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
        title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
        class="product photo product-item-photo block mx-auto mb-3 h-full <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5 md:shrink-0' ?>"
        tabindex="-1"
    >
        <?= $block->getImage($product, $imageDisplayArea)
            ->setTemplate('Magento_Catalog::product/list/image.phtml')
            ->setData('custom_attributes', $imageCustomAttributes)
            ->setProductId($productId)
            ->toHtml(); ?>
    </a>
    <?php if ($product->isAvailable() && !$hideDetails): ?>
            <?= $block->getProductDetailsHtml($product) ?>
        <?php endif; ?>
    <div class="product-info flex flex-col grow pb-1">
        <div class="items-center justify-center text-primary font-semibold text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
            <a
                class="product-item-link text-sm"
                href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                :id="`slide-desc-<?= $escaper->escapeHtmlAttr($product->getId()) ?>-${$id('slider-id')}`"
            >
                <?= /* @noEscape */ $productName ?>
            </a>
        </div>

        <?php if (!$hideRatingSummary): ?>
        <div class="py-1 <?= $viewIsGrid ? '' : 'md:mx-0 md:w-auto' ?>">
            <?= $block->getReviewsSummaryHtml($product, 'short') ?>
        </div>
        <?php endif; ?>

        <?php if ($showDescription): ?>
        <div class="mt-2 mb-1 items-center justify-center text-primary text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
            <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
        </div>
        <?php endif; ?>

        <?php if ($isProductGroupedOrBundle): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the options chosen on the product page')) ?>
            </span>
        <?php endif; ?>

        <div class="pt-1 text-gray-900"
             x-data="initPriceBox()"
             x-defer="intersect"
             @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);"
        >
            <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
        </div>

        <div class="mt-auto flex flex-wrap items-center gap-y-4 gap-x-2
            <?= $viewIsGrid ? '' : 'md:justify-center' ?>">
            <?php if ($product->isSaleable()): ?>
                <?php if ($isProductGroupedOrBundle): ?>
                <a
                    href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                    class="p-1 w-full btn btn-primary justify-center rounded-full bg-purple text-sm"
                    title="<?= $escaper->escapeHtmlAttr(__('Configure %1 on the product page')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Configure %1 on the product page', $productName)) ?>"
                >

                    <span class="ml-2 inline <?= $viewIsGrid ? 'md:ml-0 lg:ml-2 lg:inline' : '' ?>">
                        <?= $escaper->escapeHtml(__('Configure')) ?>
                    </span>
                </a>
                <?php else: ?>
                <button
                    class="p-1 w-full btn btn-primary justify-center rounded-full bg-purple text-sm"
                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                    data-addto="cart"
                >
                    <span class="ml-2 inline <?= $viewIsGrid ? 'md:ml-0 lg:ml-2 lg:inline' : '' ?>">
                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                    </span>
                </button>
                <?php endif; ?>

            <?php else: ?>
            <div class="w-auto justify-center <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>">
                <?= $block->getChildBlock('stockstatus')->setData('product', $product)->toHtml() ?>
            </div>
            <?php endif; ?>
            <div class="grid absolute top-0 right-0 mt-2 mr-2 gap-1 wish-comp-icon hidden">
                <?php if ($showAddToWishlist): ?>
                <button x-data="initWishlist()"
                        x-defer="intersect"
                        @click.prevent="addToWishlist(<?= (int)$productId ?>)"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
                        type="button"
                        class="rounded-full w-9 h-9 p-0 border-0 inline-flex shrink-0 items-center justify-center wishlist-hover hover:bg-violet-800"
                        data-addto="wishlist"
                >
                <svg version="1.1" id="productos" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                    viewBox="0 0 634.3 619.5" style="enable-background:new 0 0 634.3 619.5;" xml:space="preserve" class="w-6 h-6">
                <style type="text/css">
                    .st0{fill:none;stroke:#802E8B;stroke-width:38.9085;stroke-miterlimit:10;}
                </style>
                <path class="st0" d="M560.8,184.6c-20.9-74.4-95.3-120.9-169.5-105.7c-23.9,4.9-46.6,16.1-69.3,34.3c-2.6-2-5.1-3.9-7.6-5.7
                    C277.5,81,239.9,71.4,199.4,78.2c-36.6,6.1-70.7,28-93.6,59.9c-23.2,32.4-32.9,71-27.2,108.8c5.3,35.2,22,66.8,51.2,96.6
                    c46.9,47.8,93.8,95.6,140.7,143.3l32,32.6c4.3,4.4,11,10.2,19.5,10.2c0,0,0,0,0,0c8.5,0,15.5-6,19.9-10.6c16.7-17,33.3-33.9,50-50.9
                    c12.7-13,25.5-25.9,38.3-38.9c29.2-29.6,59.4-60.1,88.6-90.8C562.4,292.4,576.5,240.7,560.8,184.6z"/>
                </svg>
                </button>
                <?php endif; ?>
                <?php if ($showAddToCompare): ?>
                <button x-data="initCompareOnProductList()"
                        x-defer="intersect"
                        @click.prevent="addToCompare(<?= (int)$productId ?>)"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare') . ' ' . $productName) ?>"
                        type="button"
                        class="rounded-full w-9 h-9 p-0 border-0 inline-flex shrink-0 items-center justify-center compare-hover"
                        data-addto="compare"
                >
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                    viewBox="0 0 39.5 32.9" style="enable-background:new 0 0 39.5 32.9;" xml:space="preserve" class="w-8 h-8">
                <style type="text/css">
                    .st01{fill:#802E8C;}
                </style>
                <g>
                    <g>
                        <path class="st01" d="M8.5,19.5c0-0.4-0.3-0.7-0.7-0.7H6.5l1.2-2.9h4.7l1.2,2.9h-1.3c-0.4,0-0.7,0.3-0.7,0.7s0.3,0.7,0.7,0.7H18
                            c0.4,0,0.7-0.3,0.7-0.7s-0.3-0.7-0.7-0.7h-0.7L11.4,5.6H10L4.1,18.7H3.4c-0.4,0-0.7,0.3-0.7,0.7s0.3,0.7,0.7,0.7h4.4
                            C8.2,20.2,8.5,19.9,8.5,19.5z M10,10l1.7,4.4H8.2L10,10z"/>
                        <path class="st01" d="M25.3,18.7c-0.4,0-0.7,0.3-0.7,0.7s0.3,0.7,0.7,0.7h6.6c2.4,0,4.4-2,4.4-4.4c0-1.8-1.1-3.4-2.7-4
                            c0.8-0.7,1.2-1.5,1.2-2.5c0-2-2-3.7-4.4-3.7h-5.1c-0.4,0-0.7,0.3-0.7,0.7s0.3,0.7,0.7,0.7H26v11.7H25.3z M28.9,7.1h1.5
                            c0.8,0,1.5,1,1.5,2.2s-0.7,2.2-1.5,2.2h-1.5V7.1z M28.9,12.9h1.5c1.6,0,2.9,1.3,2.9,2.9c0,1.6-1.3,2.9-2.9,2.9h-1.5V12.9z"/>
                        <path class="st01" d="M26,30.4l-4.4-5.8l-4.4,5.8H26z"/>
                        <path class="st01" d="M36.3,21.7c0,0.8-0.7,1.5-1.5,1.5H7c-0.8,0-1.5-0.7-1.5-1.5H4.1c0,1.6,1.3,2.9,2.9,2.9h14.6h13.2
                            c1.6,0,2.9-1.3,2.9-2.9H36.3z"/>
                    </g>
                </g>
                </svg>
                </button>
                <?php endif; ?>
                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                    <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php if ($product->isSaleable()): ?>
</form>
<?php else: ?>
</div>
<?php endif; ?>
