<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() &&
    $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button type="submit"
            name="save_and_share"
            title="<?= $escaper->escapeHtmlAttr(__('Share Wish List')) ?>"
            class="action share btn btn-secondary text-purple px-4 py-1">
        <span><img class="h-[25px] w-[25px] mr-2" src="<?= $this->getViewFileUrl('images/wishlist/share-icon.svg') ?>" alt=""></span>
        <span>
            <?= $escaper->escapeHtml(__('Share')) ?>
        </span>
    </button>
<?php endif;?>
