<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit"
            name="do"
            title="<?= $escaper->escapeHtmlAttr(__('Update Wish List')) ?>"
            class="update btn btn-secondary text-purple px-4 py-1">
        <span><img class="h-[20px] w-[20px] mr-2" src="<?= $this->getViewFileUrl('images/wishlist/refresh-icon.svg') ?>" alt=""></span><span><?= $escaper->escapeHtml(__('Update')) ?></span>
    </button>
<?php endif;?>
