<?php if ($block->isOrderAttachmentEnabled()): ?>
<div data-bind="scope: 'Orderattachment'" style="margin-top: -1px;padding: 25px;border: 1px solid #ccc;">
                <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "Orderattachment": {
                            "component": "Mageants_Orderattachment/js/attachment",
                             "dataconfig": <?= /* @noEscape */ $block->getAttachmentConfig() ?>
                        }
                    }
                }
            }
        }
</script>
<?php endif; ?>
